apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs
spec:
  capacity:
    storage: 2Gi  
  accessModes:
    - ReadWriteMany
  storageClassName: mono-storage
  nfs:
    server: 128.199.2.250
    path: "/mnt/nfs_share"
    
