apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  capacity: 
    storage: 5Gi
  accessModes:  
    - ReadWriteOnce
  storageClassName: pv-postgres
  hostPath:
    path: "/mnt/data"